export const CLEAN_CATEGORIES = "CLEAN_CATEGORIES"


export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"


export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE"


export const CLEAN_PLAYLISTS = "CLEAN_PLAYLISTS"


export const GET_PLAYLISTS_SUCCESS = "GET_PLAYLISTS_SUCCESS"


export const GET_PLAYLISTS_FAILURE = "GET_PLAYLISTS_FAILURE"


export const CLEAN_TRACKS = "CLEAN_TRACKS"


export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS"


export const GET_TRACKS_FAILURE = "GET_TRACKS_FAILURE"


export const SET_PLAYING_TRACK = "SET_PLAYING_TRACK"


export const CLEAR_PLAYING_TRACK = "CLEAR_PLAYING_TRACK"